### ISSUE TITLE
Slow mode for chat?

### ISSUE THREAD

**Issue by TheEpTic** [m-byte/Ogar-client#1]
Is there a way of slowing down the chat? Users are flooding the chat and crashing clients.

**Comment by m-byte** [comment]
Messages could be filtered either by prroximity, or once user management is done, that could be used to filter friends

**Comment by m-byte** [comment]
Sorry, hit the wrong button

**Comment by vram4** [comment]
Ive already implemented a chat delaying system in my chat branch of Ogar
